/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychuoicuahang;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlychuoicuahang.UserSales;
import quanlychuoicuahang.NhanVien;
//import testckproduct;

/**
 *
 * @author ACER
 */
public class main extends javax.swing.JFrame {

    String screen;
    String a;
    AccountDao accountdao1 = new AccountDao();
    ArrayList<product> listP = new ArrayList<>();
    Date date = new Date(WIDTH);
//    CTHD hf = new CTHD(ABORT, screen, ABORT);
//    private String money;
//    private String discount;
//    private String finallyTotal;

//    public main(String money, String discount, String finallyTotal){
//        this.money = money;
//        this.discount = discount;
//        this.finallyTotal = finallyTotal;
//    }
    /**
     * Creates new form main
     */
//    public static String manv;
    private int dataconstructor;
    private static NhanVien staff;
//    public static String manv;
//    public ArrayList<product> list = new ArrayList<>();

    public main(NhanVien staff) {
        initComponents();
        this.staff = staff;
    }

    public main(int dataconstructor, NhanVien staff, ArrayList<product> listP) {
        initComponents();
        this.dataconstructor = dataconstructor;
        this.staff = staff;
        this.listP = listP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        btn_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        screen_text_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        screen_text_quatity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        signIn = new javax.swing.JToggleButton();
        da_co_button = new javax.swing.JRadioButton();
        chua_co_button = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton10.setText("1");

        jToggleButton4.setText("jToggleButton1");

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setAlignmentX(1.0F);
        jPanel2.setAlignmentY(1.0F);

        screen_text_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        screen_text_id.setAlignmentX(1.0F);
        screen_text_id.setAlignmentY(1.0F);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nhập mã sản phẩm");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nhập số lượng ");

        screen_text_quatity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        screen_text_quatity.setAlignmentX(1.0F);
        screen_text_quatity.setAlignmentY(1.0F);

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(screen_text_quatity)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(screen_text_id)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(screen_text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(screen_text_quatity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Thanh toán");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Bạn có thẻ thành viên chưa?");

        signIn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        signIn.setText("Truy cập");
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInMouseClicked(evt);
            }
        });
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        btn_group.add(da_co_button);
        da_co_button.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        da_co_button.setText("Đã có");
        da_co_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                da_co_buttonActionPerformed(evt);
            }
        });

        btn_group.add(chua_co_button);
        chua_co_button.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chua_co_button.setText("Chưa có");
        chua_co_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chua_co_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Cái giá phải trả: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(da_co_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chua_co_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(da_co_button)
                        .addGap(9, 9, 9)
                        .addComponent(chua_co_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of products", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên hàng", "Giá", "Mã hàng", "Số lượng"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(3, 3, 3))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void calculate() {
        if (a.contains("+")) {
            int index = a.indexOf("+");
            String left = a.substring(0, index);
            String right = a.substring(index + 1, a.length());

            int leftInt = Integer.parseInt(left);
            int rightInt = Integer.parseInt(right);
            System.out.println("left " + left);
            System.out.println("right: " + right);

            int sum = leftInt + rightInt;

            System.out.println("sum: " + sum);
            screen_text_id.setText(Integer.toString(sum));

        }
        if (a.contains("-")) {
            int index = a.indexOf("-");
            String left = a.substring(0, index);
            String right = a.substring(index + 1, a.length());

            int leftInt = Integer.parseInt(left);
            int rightInt = Integer.parseInt(right);
            System.out.println("left " + left);
            System.out.println("right: " + right);

            int sum = leftInt - rightInt;

            System.out.println("sum: " + sum);
            screen_text_id.setText(Integer.toString(sum));

        }
        if (a.contains("*")) {
            int index = a.indexOf("*");
            String left = a.substring(0, index);
            String right = a.substring(index + 1, a.length());

            int leftInt = Integer.parseInt(left);
            int rightInt = Integer.parseInt(right);
            System.out.println("left " + left);
            System.out.println("right: " + right);

            int sum = leftInt * rightInt;

            System.out.println("sum: " + sum);
            screen_text_id.setText(Integer.toString(sum));

        }
        if (a.contains("/")) {
            int index = a.indexOf("/");
            String left = a.substring(0, index);
            String right = a.substring(index + 1, a.length());

            float leftInt = Float.parseFloat(left);
            float rightInt = Float.parseFloat(right);
            System.out.println("left " + left);
            System.out.println("right: " + right);

            float sum = leftInt / rightInt;

            System.out.println("sum: " + sum);
            screen_text_id.setText(Float.toString(sum));

        }
    }

    public int ThanhToan() {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int sum = 0;
        for (product p : listP) {
            sum += p.getAmount() * p.getProductPrice();
        }
        return sum;
    }
//    
//    public String totalMoney(){
//        String a = String.valueOf(ThanhToan());
//        return a;
//    }

    public void showData(ArrayList<product> lp) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
//        System.out.println(""+listP.size());
        int stt = 1;
        for (product p : lp) {
            model.addRow(new Object[]{
                stt, p.getProductName(), p.getProductPrice(), p.getProductId(), p.getAmount()
            });
            stt++;
        }
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, 4).toString().equals("0")) {
                model.removeRow(i);
            }
        }
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            jTable1.setValueAt(String.valueOf(i + 1), i, 0);
        }
    }
    private void da_co_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_da_co_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_da_co_buttonActionPerformed

    public ArrayList<product> newList() {
        ArrayList<product> newlist = new ArrayList<>();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            newlist.add(new product(jTable1.getValueAt(i, 1).toString(), jTable1.getValueAt(i, 3).toString(), Integer.valueOf(jTable1.getValueAt(i, 2).toString()), Integer.valueOf(jTable1.getValueAt(i, 4).toString())));
        }
        return newlist;
    }
    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO add your handling code here:

//        System.out.println("" + this.m);
        if (da_co_button.isSelected()) {
            try {
//                list = newList();
                UserSales b = new UserSales(ThanhToan(), staff, listP);
                b.setVisible(true);
                this.setVisible(false);
//                listP.clear();
//                System.out.println("" + listP.s);
            } catch (Exception e) {
                System.out.println("lỗi: " + e);
            }
        } else if (chua_co_button.isSelected()) {
            try {
//                list = newList();
                SignUp signup = new SignUp(ThanhToan(), staff, listP);
                signup.setVisible(true);
                main.super.setVisible(false);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_signInActionPerformed

//    public void showData(Array){
//        
//    }
//    
    public static void main(String[] args) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main(staff).setVisible(true);
            }
        });
    }
    private void signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signInMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int total = ThanhToan();
        String sum = String.valueOf(total);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int sohd = accountdao1.SoHD() + 1;
        System.out.println("" + sohd);
        LocalDate date = java.time.LocalDate.now();
        String SDT = "";
//        System.out.println(""+sohd);
//        HoaDon hoadon = new HoaDon(SDT, Date.valueOf(date), sohd, manv, total);

        try {
            Connection con = new ConnectDataBase().getConnection();

            String sql = "INSERT INTO KHACHANG (SDT, HOTEN, POINT, RANKED)" + "VALUES(?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, String.valueOf(sohd));
            System.out.println("" + String.valueOf(sohd));
            pst.setString(2, "Others");
            pst.setFloat(3, 0);
            pst.setInt(4, 0);

            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("" + e);
        }

        try {
            Connection con = new ConnectDataBase().getConnection();

            String sql = "insert into HoaDon (SOHD, NGHD, SDT, MANV, TRIGIA)" + "values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, sohd);
            pst.setDate(2, Date.valueOf(date));
            pst.setString(3, String.valueOf(sohd));
            System.out.println("" + String.valueOf(sohd));
            pst.setString(4, this.staff.getMaNV());
            pst.setInt(5, total);

            pst.executeUpdate();
            System.out.println("Them thanh cong");
        } catch (Exception e) {
            System.out.println("" + e);
        }

        for (product p : listP) {
            try {
                Connection con = new ConnectDataBase().getConnection();
                String sql = "insert into CTHD (SOHD, MASP, SL)" + "values(?,?,?)";

                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, sohd);
                pst.setString(2, p.getProductId());
                pst.setInt(3, p.getAmount());

                pst.executeUpdate();
                System.out.println("Them thanh cong");
            } catch (Exception e) {
                System.out.println("" + e);
            }

            try {
                Connection con = new ConnectDataBase().getConnection();
                String sql = "SELECT DBO.SANPHAM.AMOUNT FROM DBO.SANPHAM WHERE DBO.SANPHAM.MASP = ?";

                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, p.getProductId());
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    int amount = Integer.valueOf(rs.getString(1));
                    int newAmount = amount - p.getAmount();
                    try {
                        Connection con1 = new ConnectDataBase().getConnection();
                        String query = "UPDATE DBO.SANPHAM SET DBO.SANPHAM.AMOUNT = ? WHERE DBO.SANPHAM.MASP = ?";
                        PreparedStatement pst1 = con1.prepareStatement(query);
                        pst1.setInt(1, newAmount);
                        pst1.setString(2, p.getProductId());

                        pst1.executeUpdate();

                    } catch (Exception e) {
                        System.out.println("" + e);
                    }
                }

            } catch (Exception e) {
            }
        }
        ShowInThanhToan(total);
        sohd++;
    }//GEN-LAST:event_jButton1MouseClicked

    public void ShowInThanhToan(int a) {
        jLabel5.setText(String.valueOf(a));
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//                int amount = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        screen_text_id.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString() + "*" + jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked
    private void tinhtien() {
        int sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Integer.valueOf(jTable1.getValueAt(i, 2).toString()) * Integer.valueOf(jTable1.getValueAt(i, 4).toString());
        }
        jLabel5.setText(String.valueOf(sum));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new Bill(staff, "Others", java.time.LocalDate.now(), listP, this.ThanhToan(), 0).setVisible(true);
        main.super.setVisible(false);
//        listP.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chua_co_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chua_co_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chua_co_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        screen_text_id.setText("");
        screen_text_quatity.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private int check(String a, int b) {
        int flag = 0;
        for (product p : listP) {
            if (p.getProductId().compareToIgnoreCase(a) == 0) {
                if (b != 0) {
                    p.setAmount(b);
//                    return 1;
                } else {
                    listP.remove(p);
//                    return 1;
                }
                return 1;
            }
        }
        return 0;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String masp = screen_text_id.getText();
        int amount = Integer.valueOf(screen_text_quatity.getText());
        product sanpham = new product();
        if (check(masp, amount) == 0) {
            try {
                Connection con = new ConnectDataBase().getConnection();

                String query = "SELECT TENSP, MASP, PRICE FROM DBO.SANPHAM WHERE DBO.SANPHAM.MASP = ?";
                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, masp);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    sanpham.setProductName(rs.getString(1));
                    sanpham.setProductId(rs.getString(2));
                    sanpham.setProductPrice(rs.getInt(3));
                    sanpham.setAmount(amount);
                    System.out.println("" + sanpham.getProductName());
                    listP.add(sanpham);
                }
            } catch (Exception e) {
                System.out.println("" + e);
            }
        }
        showData(listP);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JRadioButton chua_co_button;
    private javax.swing.JRadioButton da_co_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField screen_text_id;
    private javax.swing.JTextField screen_text_quatity;
    private javax.swing.JToggleButton signIn;
    // End of variables declaration//GEN-END:variables
}
